name: vksr
channels:
   - pytorch
   - defaults
dependencies:
   - pip
   - python=3.9.25
   - pytorch::faiss-gpu=1.9.0
   - pip:
      - point-cloud-utils==0.34.0
      - scikit-image==0.24.0
      - --extra-index-url https://download.pytorch.org/whl/cu128
      - torch==2.8.0
      - trimesh==4.10.1